is_multi_thead: false
num_image_cal: 15
size_chess: 12
corner_chess_size: [10, 10]
qr_version: 1
qr_box_size: 12
qr_border: 2
radius_c_chess: 45
minDist: 60
param1: 160
param2: 20
minRadius: 10
maxRadius: 50
camera1_id: 0
camera2_id: 1
on_cam1: true
on_cam2: true
on_cam1Hsv: false
on_cam2Hsv: false
on_cam1Ycbcr: false
on_cam2Ycbcr: false
on_cam1FTI: false
on_cam2FTI: false
on_config: false
on_show_cam1: false
on_show_cam2: false
on_controller: false
on_black_points_touch_screen: false
on_paint_test: true
on_debug: true
gamma1: 0.6
gamma2: 0.8
noseCam1: [3, 3]
noseCam2: [3, 3]
fillCam1_01:
  - [[0, 90, 10], [35, 190, 150]]
  - [[0, 0, 0], [255, 180, 135]]
fillCam2_01:
  - [[0, 90, 10], [35, 190, 150]]
  - [[0, 0, 0], [255, 180, 135]]
is_cam1_flip: false
is_cam2_flip: false
cam1_flip_mode: -1
cam2_flip_mode: -1
cam1_exposure: -1.0
cam1_exposure_auto: 3
cam2_exposure: -6.0
cam2_exposure_auto: 3
urlcam1: "http://192.168.137.155:8080/shot.jpg"
urlcam2: "http://192.168.137.182:8080/shot.jpg"
fps_cam1: 15
fps_cam2: 15
minDisparity: 15
numDisparitiesDepth: 64
blockSizeDepth: 15
FramePerProcess: 1
maxFamesClicked: 5
is_flip_mouse: true
delta_Point: [0, 0]
n_points_touch: 1
deltaContoursClicked: 3
maxRadiusFigueWithFigueShallow: 12
is_debug_clicked: false
numEleArgvan: 5
numAverageMouseMove: 8
time_delay_press: 0.1
time_delay_right_click: 0.8
circle_in_right_click: 60
maxRadiusFigueContour: 10
color_nonClicked: [0, 255, 0]
color_clicked: [0, 0, 255]
show_FPS_console: false
size_window: [640, 480]
fullscreensize: [1920, 1080]
set_detect_value_qr: ["tl", "tr", "bl", "br"]
core_value_qr: "bincase-core"
delta_point_qr: [5, 5]
delta_point_chess: [25, 30]
delta_point_circle: [25, 25]
